name: Build and Deploy SQL Project

on:
  push:
    branches:
      - main  # Run only on commit to main branch

jobs:
  build-deploy:
    runs-on: self-hosted  # Use your own machine
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Use .NET 6 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore project
      run: dotnet restore MyDatabase.sqlproj

    - name: Build .dacpac
      run: dotnet build MyDatabase.sqlproj --configuration Debug

    - name: Deploy to Local SQL Server
      run: |
        & "C:\Tools\SqlPackage\SqlPackage.exe" `
        /Action:Publish `
        /SourceFile:"bin\Debug\MyDatabase.dacpac" `
        /TargetConnectionString:"Data Source=LAPTOP-GLGJ69LR\SQLEXPRESS;Initial Catalog=DevDB;Integrated Security=True;TrustServerCertificate=True"
